<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSslgcgc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSslgcgc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSslgcgc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSslgcgc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSslgcgc\appProdProjectContainer([
    'container.build_hash' => 'Sslgcgc',
    'container.build_id' => '6ef287de',
    'container.build_time' => 1752209289,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSslgcgc');
