<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVfztrnp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVfztrnp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVfztrnp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVfztrnp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVfztrnp\appProdProjectContainer([
    'container.build_hash' => 'Vfztrnp',
    'container.build_id' => 'bdc460e1',
    'container.build_time' => 1752206104,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVfztrnp');
